### ISSUE TITLE
invisible snakes

### ISSUE THREAD

**Issue by kilian2** [KielerGames/ringofsnakes#103]
there seems to be a bug where some snakes (bots) are invisible. Also applies if they are very close to the player, so it is not a issue with the view range.

**Comment by tim-we** [comment]
I think this will boil down to the client deleting data of a snake because it is out of range and the server thinks the client still knows that data and does not re-send it. Maybe there is a another reason for this but for a start we could change the debug GUI to display snakes/chunks the client should know about in a different color. We could also log which chunks or snakes get removed in the client.

**Comment by tim-we** [comment]
Is this still a bug? I assume its not as the client has been rewritten since (the new version was merged on Feb 12, 2022). Please create a new issue if this still occurs.
