### ISSUE TITLE
Snake collision does not always work

### ISSUE THREAD

**Issue by kilian2** [KielerGames/ringofsnakes#113]
I saw a bot slithering through me, without dying. Seems to be quite rare.

**Comment by tim-we** [comment]
![image](https://user-images.githubusercontent.com/10491533/159187216-4cf53769-7087-4767-bdfd-f74fc4570de3.png)

I think this is whats happening, though this just speculation on my part. If this is indeed the issue possible fixes are:
- add additional points to the `pathData` list, see https://github.com/KielerGames/ringofsnakes/blob/d22557dda4fec24d0b2caf243cb215bda28dcbd7/server/src/main/java/game/snake/GrowingSnakeChunk.java#L88
- instead test the distance of line segments (head position change and consecutive points in `pathData`)

I would prefer the second approach though I am not sure how difficult that is to implement and how expensive such a computation is.

**Comment by tim-we** [comment]
So I was wrong, the picture above is not accurate and this is not the cause of the bug (as discussed). The issue seems to be growing snakes chunks (`GrowingSnakeChunk` obviously but also `FinalSnakeChunk` if the snake width increases). The bounding box of snake chunks can grow such that it could intersect world chunks it did not previously "touch". However these growing chunks are not added to the "new" world chunk and thus not necessarily considered in the collision checking.

**Comment by tim-we** [comment]
PRs #152 and #157 address this issue and fix it for the most part but there are still some minor edge cases left to consider.
